version: '3.8'

services:
  backend:
    build: .
    container_name: til-backend
    ports:
      - '4000:4000'
    env_file:
      - .env.docker
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
